
import React from 'react';

export const COLORS = {
  yellow: '#F1B95B',
  cream: '#F7F1E5',
  pink: '#F6CDC4',
  sage: '#89A7A1',
  salmon: '#F08A82',
};

export const ICONS = {
  dashboard: (className: string) => (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
    </svg>
  ),
  discover: (className: string) => (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
    </svg>
  ),
  sizeFinder: (className: string) => (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01" />
    </svg>
  ),
  profile: (className: string) => (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
    </svg>
  ),
  history: (className: string) => (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
    </svg>
  ),
  compare: (className: string) => (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
    </svg>
  ),
  add: (className: string) => (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
    </svg>
  ),
  scan: (className: string) => (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.01M16 20h4M4 12h4m12 0h.01M5 8h2a1 1 0 001-1V5a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1zm12 0h2a1 1 0 001-1V5a1 1 0 00-1-1h-2a1 1 0 00-1 1v2a1 1 0 001 1zM5 20h2a1 1 0 001-1v-2a1 1 0 00-1-1H5a1 1 0 00-1 1v2a1 1 0 001 1z" />
    </svg>
  ),
  passport: (className: string) => (
    <img src="https://i.postimg.cc/9fbjbgG2/MAQ-(2).png" className={`${className} object-contain`} alt="Global Passport" />
  ),
  pin: (className: string) => (
    <img src="https://i.postimg.cc/Gt6PG0rK/Pin.png" className={`${className} object-contain`} alt="Pin" />
  ),
  admin: (className: string) => (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
    </svg>
  ),
  snapshop: (className: string) => (
    <svg className={className} fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z" />
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 13a3 3 0 11-6 0 3 3 0 016 0z" />
    </svg>
  ),
};

export const TRANSLATIONS = {
  en: {
    appName: "Maqasee",
    tagline: "Your perfect size, everywhere.",
    getStarted: "Get Started",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    dashboard: "Home",
    sizeFinder: "Size",
    discover: "Styles",
    profile: "Profile",
    settings: "Settings",
    yourSizeToday: "Your size today",
    measurements: "Measurements",
    completion: "Completion",
    fitPref: "Fit Preference",
    newMeasurement: "New Measurement",
    height: "Height",
    weight: "Weight",
    neck: "Neck",
    chest: "Chest",
    waist: "Waist",
    hips: "Hips",
    shoulder: "Shoulder",
    sleeve: "Sleeve",
    inseam: "Inseam",
    thigh: "Thigh",
    foot: "Foot",
    tight: "Tight",
    regular: "Regular",
    oversized: "Oversized",
    platform: "Platform",
    category: "Category",
    findMySize: "Find Sizes",
    confidence: "Confidence",
    welcome: "Welcome back!",
    save: "Save",
    next: "Next",
    back: "Back",
    finish: "Finish",
    step: "Step",
    email: "Email",
    password: "Password",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    loading: "Loading...",
    errorAuth: "Authentication failed. Please check your credentials.",
    successSave: "Profile saved successfully!",
    metricUnit: "cm",
    weightUnit: "kg",
    totalMetrics: "Total metrics",
    profileComplete: "Profile complete",
    noData: "No measurements yet. Start by adding one!",
    history: "History",
    recentSearch: "Recent Search",
    bodyVault: "Body Vault",
    lastUpdated: "Last updated",
    torso: "Torso",
    lowerBody: "Lower Body",
    general: "General",
    noHistory: "No searches yet",
    viewAll: "View All",
    editProfile: "Edit Measurements",
    stretchTolerance: "Stretch Tolerance",
    low: "Low",
    medium: "Medium",
    high: "High",
    sizePassport: "Size Passport",
    sharePassport: "Share Size DNA",
    yourSizeDna: "Your Size DNA",
    historyTimeline: "Search Timeline",
    aiInsight: "AI Insight",
    scanning: "Scanning...",
    scanNow: "Body Scan",
    scanHelper: "Align your body with the frame",
    aiAdvicePrompt: "As a professional fit expert, give a 1-sentence friendly advice for a user with these stats and preferences.",
    invalidNumber: "Please enter a valid number",
    outOfRange: "Value is out of a realistic range",
    shareTitle: "My Maqasee Size DNA",
    shareText: "Check out my body measurements and fit preferences on Maqasee!",
    shareSuccess: "DNA copied to clipboard!",
    shareError: "Couldn't share right now.",
    toastCopied: "Size DNA copied to clipboard!",
    toastSaved: "Preferences saved locally & in cloud",
    shoes: "Footwear",
    tops: "Tops",
    bottoms: "Bottoms",
    dresses: "Dresses",
    abaya: "Abaya",
    dishdasha: "Dishdasha",
    categorySelect: "Select Category",
    profileName: "Profile Name",
    addProfile: "Add Friend",
    switchProfile: "Switch Profile",
    myself: "Myself",
    realityCheck: "AI Reality Check",
    aiVerificationPrompt: "As a health and tailoring expert, briefly check if these measurements are realistic for a human. If they are very strange, mention it kindly.",
    measurementsVerified: "Measurements look consistent!",
    measurementsUnusual: "Some values look unusual. Please double check.",
    stylePersona: "Style Persona",
    yourBestFits: "Your Best Fits",
    aiPersonaPrompt: "Based on these measurements (Height: {height}cm, Chest: {chest}cm, Waist: {waist}cm) and past feedback ({feedback}), generate a 3-word stylish persona title and a 1-sentence fit advice. Mention feedback if relevant. Format: Title | Advice.",
    discoveryTitle: "Styles",
    shopNow: "Shop Category",
    basedOnDna: "Based on your DNA",
    styleAdvice: "Style Advice",
    rateFit: "Rate the fit",
    howWasFit: "How did it fit?",
    tooTight: "Too Tight",
    perfect: "Perfect",
    tooLoose: "Too Loose",
    feedbackSaved: "Feedback saved. AI is learning!",
    aiLearning: "AI is learning your style...",
    verifiedFit: "Verified Fit",
    sizeFriends: "Size Friends",
    relationship: "Relationship",
    friend: "Friend",
    family: "Family",
    self: "Self",
    whosThisFor: "Who is this for?",
    friendDna: "Friend DNA",
    groupRecommendation: "Group Recommendation",
    sizesForAll: "Sizes for everyone",
    checkEveryone: "Check for everyone",
    forSomeoneElse: "For someone else",
    recommendedSize: "Recommended Size",
    deleteProfile: "Delete Profile",
    confirmDelete: "Are you sure?",
    deleteWarning: "This will permanently remove this profile and its measurements.",
    cancel: "Cancel",
    confirm: "Yes, Delete",
    rename: "Rename Profile",
    editMeta: "Profile Details",
    units: "Units",
    metric: "Metric",
    imperial: "Imperial",
    inches: "in",
    pounds: "lb",
    resetDNA: "Reset Measurements",
    confirmReset: "Are you sure you want to clear all data?",
    vaultUpdated: "Body Vault updated",
    offlineMode: "Offline Mode",
    usingCache: "Using cached data",
    backOnline: "Back Online",
    compare: "Compare Profiles",
    selectProfile: "Select Profile",
    diff: "Difference",
    noChange: "No Change",
    friendsHub: "Friends Hub",
    manageFriends: "Manage your size circle",
    globalPassport: "Global Size Passport",
    internationalSizes: "International Sizes",
    us: "US (Standard)",
    uk: "UK (Standard)",
    eu: "EU (Standard)",
    jp: "JP (Standard)",
    regionalMapping: "Regional Mapping",
    compareAdvice: "Comparison helps you understand how different fits will feel across your circle of friends and family.",
    friendsAdvice: "Use the Size Finder and switch profiles to get perfect sizing for your family and friends.",
    giftRecommendations: "Gift Recommendations",
    gender: "Gender",
    men: "Male",
    women: "Female",
    adminPanel: "Admin Panel",
    admin: "Admin",
    manageCharts: "Manage Size Charts",
    addChart: "Add New Chart",
    platformName: "Platform Name",
    editChart: "Edit Size Chart",
    deleteChart: "Delete Chart",
    totalCharts: "Total Charts",
    activePlatforms: "Active Platforms",
    snapShop: "SnapShop",
    snapProduct: "Snap Product",
    snapHelper: "Take a clear photo of the clothing item",
    findingProducts: "Finding your perfect fits...",
    fitScore: "Fit Score",
    noProductsFound: "No similar products found in your size yet.",
    selectKey: "Enable AI Shopping",
    billingRequired: "This feature requires a Pro AI session.",
    viewBilling: "View Billing Info",
    analyzingImage: "Analyzing style and details...",
    searchingWeb: "Searching the web...",
    checkingFit: "Checking your DNA fit...",
    heroTitle: "Shop Better by Tracking Your Size DNA",
    heroDesc: "Experience smarter, real-time fashion insights with seamless body tracking and empowering you to take control of your style every day.",
    startJourney: "Start Your Journey",
    featuresTitle: "The Future of Shopping",
    feature1Title: "Body DNA Vault",
    feature1Desc: "Securely store and manage your precise measurements. Gain insights into patterns and boost selfawareness.",
    feature2Title: "Snap & Shop Magic",
    feature2Desc: "Identifies clothing items from photos and matches them with your DNA for a guaranteed fit every time.",
    feature3Title: "Global Size Passport",
    feature3Desc: "One profile, every region. Instantly convert your measurements to US, UK, EU, or JP standards.",
    testimonialsTitle: "What Our Community Says",
    accuracyStat: "100% Accuracy",
    accuracyDesc: "Clinically trusted support with 100% accuracy for every measurement and fit check.",
    getApp: "Get the App",
    footerText: "Your perfect size, anywhere in the world.",
    leadershipTitle: "Visionary Leadership",
    ceoName: "Abdullah Alenezi",
    ceoTitle: "Founder & CEO, Maqasee",
    ceoQuote: "Maqasee was built to solve a real problem people face every day, not knowing their true size. Our vision is simple: one digital size that works everywhere, respects culture, and restores confidence to how people shop.",
    ctoName: "Walid Kahil",
    ctoTitle: "Co-Founder & CTO, Maqasee",
    ctoQuote: "At Maqasee, we use AI to translate the human body into actionable data. Our technology doesn’t just measure; it learns, adapts, and improves accuracy over time, creating a true Size DNA that scales across brands and markets.",
    dubai: "Dubai",
    london: "London",
    newYork: "New York",
    shopWorldTitle: "Shop The World",
    shopWorldDesc: "Unlock global style. Instantly convert your DNA profile to any regional sizing standard.",
    traditionalShopping: "Traditional Shopping",
    maqaseeExperience: "Maqasee Experience",
    traditionalDesc: "Struggling with size variations and constant returns.",
    maqaseeDesc: "Experience smarter, real-time fashion insights with seamless body tracking and empowering you to take control of your style every day.",
    step1Scan: "Scan",
    step1ScanDesc: "Capture your body DNA with AI scanning.",
    step2Save: "Save",
    step2SaveDesc: "Securely vault your profile in the cloud.",
    step3Search: "Search",
    step3SearchDesc: "Find styles tailored to your unique fit.",
    step4Shop: "Shop",
    step4ShopDesc: "Global size passport for easy checkout.",
    tryMaqasee: "Try Maqasee Now",
    perkAccuracy: "100% Verified Fit Accuracy",
    perkConversion: "One-Click Global Conversion",
    perkPredictions: "AI Style DNA Predictions",
    readyToFind: "Ready to Find Your Fit?",
    joinFuture: "Join the future of fashion. Your unique DNA profile is the only size you'll ever need.",
    footerRights: "MAQASEE • GLOBAL SIZE PROTOCOL 2025",
    quote1: "\"Is this a US 10 or a UK 14?\"",
    quote2: "\"Will it be too tight in the chest?\"",
    quote3: "\"I have to return this again...\"",
    badgeScan: "DNA SCAN",
    badgeVault: "VAULT",
    badgeStyles: "STYLES",
    badgeGlobal: "GLOBAL",
    discoveryLinks: "Discovery Links",
    loginSubtitle: "Welcome back! Please enter your details.",
    signupSubtitle: "Join us to find your perfect fit.",
    notificationSettings: "Notification Settings",
    manageNotifications: "Manage your notification preferences",
    appUpdates: "App Updates",
    measurementReminders: "Measurement Reminders",
    featureAnnouncements: "New Features"
  },
  ar: {
    appName: "مقاسي",
    tagline: "مقاسك الصح في كل مكان",
    getStarted: "ابدأ الآن",
    login: "تسجيل الدخول",
    signup: "إنشاء حساب",
    logout: "تسجيل الخروج",
    dashboard: "الرئيسية",
    sizeFinder: "مقاس",
    discover: "موضة",
    profile: "ملفك ",
    settings: "الإعدادات",
    yourSizeToday: "مقاسك اليوم",
    measurements: "المقاسات",
    completion: "الاكتمال",
    fitPref: "تفضيلات الملاءمة",
    newMeasurement: "قياس جديد",
    height: "الطول",
    weight: "الوزن",
    neck: "الرقبة",
    chest: "الصدر",
    waist: "الخصر",
    hips: "الأرداف",
    shoulder: "الكتف",
    sleeve: "الكم",
    inseam: "داخل الساق",
    thigh: "الفخذ",
    foot: "القدم",
    tight: "ضيق",
    regular: "عادي",
    oversized: "واسع",
    platform: "المنصة",
    category: "الفئة",
    findMySize: "ابحث عن المقاسات",
    confidence: "مستوى الثقة",
    welcome: "أهلاً بك مجدداً!",
    save: "حفظ",
    next: "التالي",
    back: "رجوع",
    finish: "إنهاء",
    step: "خطوة",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    noAccount: "ليس لديك حساب؟",
    hasAccount: "لديك حساب بالفعل؟",
    loading: "جاري التحميل...",
    errorAuth: "فشل المصادقة. يرجى التحقق من بياناتك.",
    successSave: "تم حفظ الملف الشخصي بنجاح!",
    metricUnit: "سم",
    weightUnit: "كجم",
    totalMetrics: "إجمالي المقاسات",
    profileComplete: "اكتمال الملف",
    noData: "لا توجد مقاسات بعد. ابدأ بإضافة مقاسك الأول!",
    history: "السجل",
    recentSearch: "آخر بحث",
    bodyVault: "خزنة القياسات",
    lastUpdated: "آخر تحديث",
    torso: "الجذع",
    lowerBody: "الجزء السفلي",
    general: "عام",
    noHistory: "لا يوجد سجل للبحث",
    viewAll: "عرض الكل",
    editProfile: "تعديل القياسات",
    stretchTolerance: "تحمل التمدد",
    low: "منخفض",
    medium: "متوسط",
    high: "عالي",
    sizePassport: "جواز سفر المقاس",
    sharePassport: "مشاركة المقاس",
    yourSizeDna: "مقاس",
    historyTimeline: "تاريخ عمليات البحث",
    aiInsight: "رؤية الذكاء الاصطناعي",
    scanning: "جاري المسح...",
    scanNow: "مسح الجسم",
    scanHelper: "قم بمحاذاة جسمك مع الإطار",
    aiAdvicePrompt: "كخبير ملاءمة محترف، قدم نصيحة ودية من جملة واحدة لمستخدم بهذه البيانات والتفضيلات.",
    invalidNumber: "يرجى إدخل رقم صحيح",
    outOfRange: "القمة خارج النطاق المنطقي",
    shareTitle: "مقاسي",
    shareText: "اطلع على قياسات جسمك وتفضيلات الملاءمة الخاصة بي على تطبيق مقاسي!",
    shareSuccess: "تم نسخ المقاس!",
    shareError: "تعذرت المشاركة حالياً.",
    toastCopied: "تم نسخ المقاس إلى الحافظة!",
    toastSaved: "تم حفظ التفضيلات سحابياً",
    shoes: "الأحذية",
    tops: "القطع العلوية",
    bottoms: "القطع السفلية",
    dresses: "الفساتين",
    abaya: "عباية",
    dishdasha: "دشداشة",
    categorySelect: "اختر الفئة",
    profileName: "اسم الملف",
    addProfile: "إضافة صديق",
    switchProfile: "تبديل الملف",
    myself: "أنا",
    realityCheck: "فحص الذكاء الاصطناعي",
    aiVerificationPrompt: "بصفتك خبيرًا في الصحة والخياطة، تحقق باختصار مما إذا كانت هذه القياسات واقعية للإنسان. إذا كانت غريبة جدًا، اذكر ذلك بلطف.",
    measurementsVerified: "القياسات تبدو منطقية!",
    measurementsUnusual: "بعض القيم تبدو غير معتادة. يرجى التأكد.",
    stylePersona: "شخصية الأناقة",
    yourBestFits: "أفضل ما يناسبك",
    aiPersonaPrompt: "بناءً على هذه القياسات (الطول: {height}سم، الصدر: {chest}سم، الخصر: {waist}سم) والتعليقات السابقة ({feedback})، قم بإنشاء عنوان شخصية أنيقة من 3 كلمات ونصيحة ملاءمة من جملة واحدة. اذكر التعليقات إذا كانت ذات صلة. التنسيق: العنوان | النصيحة.",
    discoveryTitle: "موضة",
    shopNow: "تسوق الفئة",
    basedOnDna: "بناءً على بصمتك",
    styleAdvice: "نصيحة التنسيق",
    rateFit: "قيم المقاس",
    howWasFit: "كيف كان المقاس؟",
    tooTight: "ضيق جداً",
    perfect: "مثالي",
    tooLoose: "واسع جداً",
    feedbackSaved: "تم حفظ التقييم. الذكاء الاصطناعي يتعلم!",
    aiLearning: "الذكاء الاصطناعي يتعلم أسلوبك...",
    verifiedFit: "مقاس مؤكد",
    sizeFriends: "أصدقاء المقاس",
    relationship: "العلاقة",
    friend: "صديق",
    family: "عائلة",
    self: "أنا",
    whosThisFor: "لمن هذا الملف؟",
    friendDna: "بصمة الصديق",
    groupRecommendation: "توصية للمجموعة",
    sizesForAll: "مقاسات الجميع",
    checkEveryone: "التحقق للجميع",
    forSomeoneElse: "لشخص آخر",
    recommendedSize: "المقاس الموصى به",
    deleteProfile: "حذف الملف",
    confirmDelete: "هل أنت متأكد؟",
    deleteWarning: "سيؤدي هذا إلى حذف هذا الملف وقياساته بشكل دائم.",
    cancel: "إلغاء",
    confirm: "نعم، احذف",
    rename: "إعادة تسمية الملف",
    editMeta: "تفاصيل الملف",
    units: "الوحدات",
    metric: "نظام متري",
    imperial: "نظام إمبراطوري",
    inches: "بوصة",
    pounds: "رطل",
    resetDNA: "إعادة تعيين القياسات",
    confirmReset: "هل أنت متأكد أنريد مسح كافة البيانات؟",
    vaultUpdated: "تم تحديث خزنة القياسات",
    offlineMode: "نمط بدون اتصال",
    usingCache: "عرض البيانات المحفوظة",
    backOnline: "متصل الآن",
    compare: "مقارنة الملفات",
    selectProfile: "اختر الملف",
    diff: "الفرق",
    noChange: "لا يوجد تغيير",
    friendsHub: "مركز الأصدقاء",
    manageFriends: "إدارة دائرة مقاساتك",
    globalPassport: "جواز سفر المقاس العالمي",
    internationalSizes: "المقاسات العالمية",
    us: "نظام أمريكي",
    uk: "نظام بريطاني",
    eu: "نظام أوروبي",
    jp: "نظام ياباني",
    regionalMapping: "توزيع الأقاليم",
    compareAdvice: "المقارنة تساعدك تفهم شلون القياسات تختلف بين ربعك وأهلك وتضمن الكل مرتاح.",
    friendsAdvice: "استخدم مكتشف المقاس وبدل بين الملفات علشان تطلع المقاس المضبوط حق أهلك وربعك.",
    giftRecommendations: "توصيات الهدايا",
    gender: "الجنس",
    men: "ذكر",
    women: "أنثى",
    adminPanel: "لوحة الإدارة",
    admin: "مسؤول",
    manageCharts: "إدارة جداول المقاسات",
    addChart: "إضافة جدول جديد",
    platformName: "اسم المنصة",
    editChart: "تعديل جدول المقاسات",
    deleteChart: "حذف الجدول",
    totalCharts: "إجمالي الجداول",
    activePlatforms: "المنصات النشطة",
    snapShop: "سناب شوب",
    snapProduct: "صور المنتج",
    snapHelper: "التقط صورة واضحة لقطعة الملابس",
    findingProducts: "نبحث عن المقاس المناسب لك...",
    fitScore: "مستوى الملاءمة",
    noProductsFound: "لم نجد منتجات مشابهة بمقاسك حالياً.",
    selectKey: "تفعيل التسوق بالذكاء الاصطناعي",
    billingRequired: "هذه الميزة تتطلب جلسة ذكاء اصطناعي متقدمة.",
    viewBilling: "معلومات الفوترة",
    analyzingImage: "نحلل الستايل والتفاصيل...",
    searchingWeb: "نبحث في الإنترنت...",
    checkingFit: "نتحقق من ملاءمة مقاسك...",
    heroTitle: "تسوق بذكاء عبر بصمة مقاسك الجسدية",
    heroDesc: "استمتع برؤى أزياء ذكية ولحظية مع تتبع سلس للجسم وتمكنك من التحكم في أسلوبك كل يوم.",
    startJourney: "ابدأ رحلتك",
    featuresTitle: "مستقبل التسوق",
    feature1Title: "خزنة البصمة الجسدية",
    feature1Desc: "قم بتخزين وإدارة قياساتك الدقيقة بأمان. احصل على رؤى حول الأنماط وزد من وعيك بجسمك.",
    feature2Title: "سحر سناب وشوب",
    feature2Desc: "يتعرف على قطع الملابس من الصور ويطابقها مع بصمتك لضمان مقاس مثالي في كل مرة.",
    feature3Title: "جواز سفر المقاس العالمي",
    feature3Desc: "ملف شخصي واحد لكل منطقة. حول قياساتك فوراً إلى المعايير الأمريكية والبريطانية والأوروبية واليابانية.",
    testimonialsTitle: "ماذا يقول مجتمعنا",
    accuracyStat: "١٠٠٪ دقة",
    accuracyDesc: "دعم موثوق به مع دقة بنسبة ١٠٠٪ لكل قياس وفحص للملاءمة.",
    getApp: "احصل على التطبيق",
    footerText: "مقاسك المثالي في أي مكان في العالم.",
    leadershipTitle: "قيادة رؤيوية",
    ceoName: "عبدالله العنزي",
    ceoTitle: "المؤسس والرئيس التنفيذي – مقاسي",
    ceoQuote: "مقاسي انبنى علشان يحل مشكلة حقيقية يواجهها الناس يوميًا: إنهم ما يعرفون مقاسهم الصح. رؤيتنا بسيطة — هوية مقاس رقمية وحدة تمشي معك بكل مكان، تحترم ثقافتنا، وترجع الثقة لطريقة تسوق الناس.",
    ctoName: "وليد كحيل",
    ctoTitle: "المؤسس المشارك والرئيس التقني – مقاسي",
    ctoQuote: "في مقاسي نستخدم الذكاء الاصطناعي علشان نحوّل جسم الإنسان إلى بيانات ذكية قابلة للاستخدام. تقنيتنا ما تقيس وبس — تتعلّم، تتطور، وتزيد دقتها مع الوقت، علشان تبني Size DNA حقيقي يشتغل مع كل العلامات والأسواق.",
    dubai: "دبي",
    london: "لندن",
    newYork: "نيويورك",
    shopWorldTitle: "تسوق حول العالم",
    shopWorldDesc: "افتح آفاق الأناقة العالمية. حول بصمتك الجسدية فوراً إلى أي معيار مقاس إقليمي.",
    traditionalShopping: "التسوق التقليدي",
    maqaseeExperience: "تجربة مقاسي",
    traditionalDesc: "معاناة مع اختلاف المقاسات والمرتجعات المستمرة.",
    maqaseeDesc: "استمتع برؤى أزياء ذكية ولحظية مع تتبع سلس للجسم وتمكنك من التحكم في أسلوبك كل يوم.",
    step1Scan: "امسح",
    step1ScanDesc: "التقط بصمة جسدك عبر المسح الذكي.",
    step2Save: "احفظ",
    step2SaveDesc: "احفظ ملفك بأمان في السحابة.",
    step3Search: "ابحث",
    step3SearchDesc: "اكتشف أزياء تناسب مقاسك الفريد.",
    step4Shop: "تسوق",
    step4ShopDesc: "جواز سفر مقاس عالمي لسهولة الدفع.",
    tryMaqasee: "جرب مقاسي الآن",
    perkAccuracy: "دقة مقاس مضمونة ١٠٠٪",
    perkConversion: "تحويل عالمي بضغطة واحدة",
    perkPredictions: "توقعات أسلوبك بالذكاء الاصطناعي",
    readyToFind: "مستعد تكتشف مقاسك الصح؟",
    joinFuture: "انضم لمستقبل الموضة. بصمة مقاسك الفريدة هي كل اللي تحتاجه.",
    footerRights: "مقاسي • بروتوكول المقاس العالمي ٢٠٢٥",
    quote1: "هذا مقاس ١٠ أمريكي ولا ١٤ بريطاني؟",
    quote2: "بيكون ضيق من ناحية الصدر? ",
    quote3: "لازم أرجعه مرة ثانية...",
    badgeScan: "بصمة الـ DNA",
    badgeVault: "خزنة المقاسات",
    badgeStyles: "ستايلات",
    badgeGlobal: "جواز عالمي",
    discoveryLinks: "روابط الاكتشاف",
    loginSubtitle: "أهلاً بك مجدداً! يرجى إدخال بياناتك.",
    signupSubtitle: "انضم إلينا لتجد مقاسك المثالي.",
    notificationSettings: "إعدادات الإشعارات",
    manageNotifications: "إدارة تفضيلات الإشعارات الخاصة بك",
    appUpdates: "تحديثات التطبيق",
    measurementReminders: "تذكير القياسات",
    featureAnnouncements: "الميزات الجديدة"
  }
};
